applicationset:
  name: argocd-applicationset-helm
  namespace: argocd
  repoURL: https://github.com/jmchar/argocd-applicationset.git
  revision: HEAD
  files:
    - services/*/earth/config.yaml
    - services/*/jupiter/config.yaml