destination:
  server: https://kubernetes.default.svc
  cluster: jupiter
  namespace: dev
application:
  name: sample-app-abc
  repoURL: https://raw.githubusercontent.com/jmchar/helm-git-repo/main
  targetRevision: 0.2.0
  helm:
    parameters: |
      - name: imageVersion
        value: 0.1.0
      - name: pcf-consul-sync.git.ref
        value: v0.1.0
      - name: gitRef
        value: v0.1.0
    valueFiles: |
      - values.yaml

obj:
  helm: |
    parameters:
      - name: imageVersion
        value: 0.1.0
      - name: pcf-consul-sync.git.ref
        value: v0.1.0
      - name: gitRef
        value: v0.1.0
    valueFiles:
      - values.yaml
