destination:
  server: https://kubernetes.default.svc
  cluster: jupiter
  namespace: dev
application:
  name: sample-app-abc
  repoURL: https://raw.githubusercontent.com/jmchar/helm-git-repo/main
  targetRevision: 0.2.0
helm: |
  parameters:
    - name: imageVersion
      value: 0.34.0
    - name: pcf-consul-sync.git.ref
      value: v0.34.0
    - name: gitRef
      value: v0.34.0
  valueFiles:
    - values.yaml
app_values: |
  image:
    repository: ghcr.io/runatlantis/atlantis
    tag: v0.19.8
    pullPolicy: IfNotPresent