destination:
  server: https://kubernetes.default.svc
  cluster: earth
  namespace: uat
application:
  name: sample-app-xyz
  repoURL: https://raw.githubusercontent.com/jmchar/helm-git-repo/main
  targetRevision: 0.1.0
  helm:
    parameters:
      - name: imageVersion
        value: 0.1.0
      - name: pcf-consul-sync.git.ref
        value: v0.1.0
      - name: gitRef
        value: v0.1.0
    valueFiles:
      - "environment/values.yaml"
      - "values.yaml"
    values: |
      imageVersion: 0.1.0
      pcf-consul-sync.git.ref: v0.1.0
      gitRef: v0.1.0
