apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jmchar/argocd-applicationset.git
        revision: HEAD
        directories:
        - path: configs/*/*
  template:
    metadata:
      namespace: argocd-'{{path[2]}}'
      name: '{{path[2]}}-{{path[1]}}'
    spec:
      project: argocd-applicationset-poc
      source:
        chart: '{{path[1]}}'
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "configs/{{path[1]}}/{{path[2]}}/values.yaml"
            - "configs/{{path[1]}}/values.yaml"
        repoURL: https://raw.githubusercontent.com/jmchar/helm-git-repo/main
        path: ''
        targetRevision: 0.1.0
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[2]}}"