apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jmchar/argocd-applicationset.git
        revision: HEAD
        files:
          - path: services/*/*/config.json
  template:
    metadata:
      namespace: argocd-'{{ destination.cluster }}'
      name: '{{ destination.cluster }}-{{ application.name }}'
    spec:
      project: argocd-applicationset-poc
      source:
        chart: '{{ application.name }}'
        repoURL: '{{ application.repoURL }}'
        path: ''
        targetRevision: '{{ application.targetRevision }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '{{ helm.valuesFiles }}'
          parameters:
            - name: imageVersion
              value: '{{ helm.imageVersion }}'
      destination:
        server: '{{ destination.server }}'
        namespace: '{{ destination.namespace }}'