apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-applicationset-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jmchar/argocd-applicationset.git
        revision: HEAD
        files:
          - path: configs/*/values.yaml
          - path: configs/*/*/values.yaml
  template:
    metadata:
      namespace: argocd-'{{cluster}}'
      name: '{{ cluster }}-{{ name }}'
    spec:
      project: argocd-applicationset-poc
      source:
        chart: '{{ name }}'
        repoURL: '{{ application.repoURL }}'
        path: ''
        targetRevision: {{ application.targetRevision }}
      destination:
        server: '{{ destination.server }}'
        namespace: '{{ destination.namespace }}'