apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.applicationset.name }}
  namespace: {{ .Values.applicationset.namespace }}
spec:
  generators:
    - git:
        repoURL: {{ .Values.applicationset.repoURL }}
        revision: {{ .Values.applicationset.revision }}
        files:
        {{- range $path := .Values.applicationset.files }}
          - path: {{ $path }}
        {{- end }}
  template:
    metadata:
      name: '{{ printf "{{ destination.cluster }}" }}-{{ printf "{{ application.name }}" }}'
      namespace: argocd-'{{ printf "{{ destination.cluster }}" }}'
      {{- if .Values.useFinalizer | default true }}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      {{- end }}
    spec:
      project: argocd-applicationset-poc
      source:
        chart: '{{ printf "{{ application.name }}" }}'
        repoURL: '{{ printf "{{ application.repoURL }}" }}'
        path: ''
        targetRevision: '{{ printf "{{ application.targetRevision }}" }}'
        helm:
          valuesFiles:
            - '{{ printf "{{ helm.valuesFiles }}" }}'
          parameters:
            - name: imageVersion
              value: '{{ printf "{{ helm.imageVersion }}" }}'
        destination:
          server: '{{ printf "{{ destination.server }}" }}'
          namespace: '{{ printf "{{ destination.namespace }}" }}'